resources:
- name: repo
  type: git
  source:
    uri: https://github.com/andreyrojasGL/jmeter-pipeline-test.git
    branch: master
jobs:
- name: job-perf-test-EventCloud-2
  plan:
  - get: repo
  - task: run-jmeter-EventCloud-2
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: jmeter
      inputs:
      -  name: repo
      outputs:
      - name: report
      run:
        path: sh
        args: 
        - -c
        - |
          set -e
          cd repo
          
          jmeter -Dlog_level.jmeter=DEBUG \
            -n -t EventCloud-full-suite.jmx -l test.jtl -j jmeter.log \
            -e -o ../report
            
          echo "==== jmeter.log ===="
          cat ./jmeter.log
          
          echo "==== Raw Test Report ===="
          cat ./test.jtl
